#pragma once

#define USB_VID 0x2E8A
#define USB_PID 0x4002

#define ITF_NUM_CDC 0
#define ITF_NUM_CDC_DATA 1
#define ITF_NUM_VENDOR 2
#define ITF_NUM_TOTAL 3

#define EPNUM_CDC_NOTIF 0x81
#define EPNUM_CDC_OUT 0x02
#define EPNUM_CDC_IN 0x82
#define EPNUM_VENDOR_OUT 0x03
#define EPNUM_VENDOR_IN 0x83
#define EP_SIZE_VENDOR 64

#define VENDOR_REQUEST_MICROSOFT 0x20
#define MS_OS_20_DESC_LEN 0x00B2
